service: example-service

frameworkVersion: '>3.0.0'

provider:
  name: aws
  runtime: go1.x
  region: ca-central-1

plugins:
  - serverless-go-plugin

functions:
  example:
    handler: ./functions/example/main.go # or just "./functions/example"
